/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Log in to the system. Returns 2 JWT tokens, access_token and refresh_token. access_token is to be used in Authorization Bearer.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh session
         * @description Refreshes the session, returning 2 new JWT tokens.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                    "text/json": components["schemas"]["RefreshRequest"];
                    "application/*+json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["Client"]>;
                        "application/json": Array<components["schemas"]["Client"]>;
                        "text/json": Array<components["schemas"]["Client"]>;
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientCreateDto"];
                    "text/json": components["schemas"]["ClientCreateDto"];
                    "application/*+json": components["schemas"]["ClientCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Client"];
                        "application/json": components["schemas"]["Client"];
                        "text/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Client"];
                        "application/json": components["schemas"]["Client"];
                        "text/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClientUpdateDto"];
                    "text/json": components["schemas"]["ClientUpdateDto"];
                    "application/*+json": components["schemas"]["ClientUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Client"];
                        "application/json": components["schemas"]["Client"];
                        "text/json": components["schemas"]["Client"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Clients/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Array<string>;
                    "text/json": Array<string>;
                    "application/*+json": Array<string>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BatchOperationResult"];
                        "application/json": components["schemas"]["BatchOperationResult"];
                        "text/json": components["schemas"]["BatchOperationResult"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Clients/batch/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Array<string>;
                    "text/json": Array<string>;
                    "application/*+json": Array<string>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BatchOperationResult"];
                        "application/json": components["schemas"]["BatchOperationResult"];
                        "text/json": components["schemas"]["BatchOperationResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Clients/inactive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["Client"]>;
                        "application/json": Array<components["schemas"]["Client"]>;
                        "text/json": Array<components["schemas"]["Client"]>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/LeadTasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["LeadTask"]>;
                        "application/json": Array<components["schemas"]["LeadTask"]>;
                        "text/json": Array<components["schemas"]["LeadTask"]>;
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LeadTaskCreateDto"];
                    "text/json": components["schemas"]["LeadTaskCreateDto"];
                    "application/*+json": components["schemas"]["LeadTaskCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LeadTask"];
                        "application/json": components["schemas"]["LeadTask"];
                        "text/json": components["schemas"]["LeadTask"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/LeadTasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LeadTask"];
                        "application/json": components["schemas"]["LeadTask"];
                        "text/json": components["schemas"]["LeadTask"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LeadTaskUpdateDto"];
                    "text/json": components["schemas"]["LeadTaskUpdateDto"];
                    "application/*+json": components["schemas"]["LeadTaskUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LeadTask"];
                        "application/json": components["schemas"]["LeadTask"];
                        "text/json": components["schemas"]["LeadTask"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/LeadTasks/lead/{leadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    leadId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["LeadTask"]>;
                        "application/json": Array<components["schemas"]["LeadTask"]>;
                        "text/json": Array<components["schemas"]["LeadTask"]>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/LeadTasks/user/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["LeadTask"]>;
                        "application/json": Array<components["schemas"]["LeadTask"]>;
                        "text/json": Array<components["schemas"]["LeadTask"]>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/LeadTasks/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["LeadTask"]>;
                        "application/json": Array<components["schemas"]["LeadTask"]>;
                        "text/json": Array<components["schemas"]["LeadTask"]>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/LeadTasks/completed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["LeadTask"]>;
                        "application/json": Array<components["schemas"]["LeadTask"]>;
                        "text/json": Array<components["schemas"]["LeadTask"]>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/LeadTasks/daterange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["LeadTask"]>;
                        "application/json": Array<components["schemas"]["LeadTask"]>;
                        "text/json": Array<components["schemas"]["LeadTask"]>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/LeadTasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["Lead2"]>;
                        "application/json": Array<components["schemas"]["Lead2"]>;
                        "text/json": Array<components["schemas"]["Lead2"]>;
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LeadCreateDto"];
                    "text/json": components["schemas"]["LeadCreateDto"];
                    "application/*+json": components["schemas"]["LeadCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Lead2"];
                        "application/json": components["schemas"]["Lead2"];
                        "text/json": components["schemas"]["Lead2"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Leads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Lead2"];
                        "application/json": components["schemas"]["Lead2"];
                        "text/json": components["schemas"]["Lead2"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LeadUpdateDto"];
                    "text/json": components["schemas"]["LeadUpdateDto"];
                    "application/*+json": components["schemas"]["LeadUpdateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Lead2"];
                        "application/json": components["schemas"]["Lead2"];
                        "text/json": components["schemas"]["Lead2"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Leads/inactive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["Lead2"]>;
                        "application/json": Array<components["schemas"]["Lead2"]>;
                        "text/json": Array<components["schemas"]["Lead2"]>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Leads/client/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    clientId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["Lead2"]>;
                        "application/json": Array<components["schemas"]["Lead2"]>;
                        "text/json": Array<components["schemas"]["Lead2"]>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Leads/assignedto/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["Lead2"]>;
                        "application/json": Array<components["schemas"]["Lead2"]>;
                        "text/json": Array<components["schemas"]["Lead2"]>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Leads/status/{status}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    status: components["schemas"]["LeadStatus"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": Array<components["schemas"]["Lead2"]>;
                        "application/json": Array<components["schemas"]["Lead2"]>;
                        "text/json": Array<components["schemas"]["Lead2"]>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Leads/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Leads/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Array<string>;
                    "text/json": Array<string>;
                    "application/*+json": Array<string>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BatchOperationResult"];
                        "application/json": components["schemas"]["BatchOperationResult"];
                        "text/json": components["schemas"]["BatchOperationResult"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Leads/batch/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Array<string>;
                    "text/json": Array<string>;
                    "application/*+json": Array<string>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["BatchOperationResult"];
                        "application/json": components["schemas"]["BatchOperationResult"];
                        "text/json": components["schemas"]["BatchOperationResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create User
         * @description Creates a new User with the given data & role
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Batch Deactivate User
         * @description Deactivates many users by their IDs
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Array<string>;
                    "text/json": Array<string>;
                    "application/*+json": Array<string>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deactivate User
         * @description Deactivates a single User by its ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Users/{userId}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reactivate User
         * @description Reactivates a single User by its ID
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/Users/batch/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Batch Reactivate User
         * @description Reactivates many users by their IDs
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": Array<string>;
                    "text/json": Array<string>;
                    "application/*+json": Array<string>;
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BatchOperationResult: {
            successIds?: Array<string>;
            failedIds?: Array<string>;
            /** Format: int32 */
            totalProcessed?: number;
            allSucceeded?: boolean;
        };
        Client: {
            /** Format: uuid */
            id?: string;
            name: string;
            coOwner?: string | null;
            dni?: string | null;
            ruc?: string | null;
            companyName?: string | null;
            phoneNumber: string;
            email: string;
            address: string;
            type: components["schemas"]["ClientType"];
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            displayName?: string | null;
        };
        Client2: {
            /** Format: uuid */
            id?: string;
            name: string;
            coOwner?: string | null;
            dni?: string | null;
            ruc?: string | null;
            companyName?: string | null;
            phoneNumber: string;
            email: string;
            address: string;
            type: components["schemas"]["ClientType"];
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            displayName?: string | null;
        } | null;
        ClientCreateDto: {
            name: string;
            coOwner?: string | null;
            dni?: string | null;
            ruc?: string | null;
            companyName?: string | null;
            phoneNumber: string;
            email: string;
            address: string;
            type: components["schemas"]["ClientType"];
        };
        /** @enum {unknown} */
        ClientType: "Natural" | "Juridico";
        ClientUpdateDto: {
            name?: string | null;
            coOwner?: string | null;
            dni?: string | null;
            ruc?: string | null;
            companyName?: string | null;
            phoneNumber?: string | null;
            email?: string | null;
            address?: string | null;
            type?: components["schemas"]["NullableOfClientType"];
        };
        Lead: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            clientId?: string | null;
            client?: components["schemas"]["Client2"];
            /** Format: uuid */
            assignedToId?: string | null;
            assignedTo?: components["schemas"]["User"];
            status: components["schemas"]["LeadStatus"];
            procedency: string;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
        } | null;
        Lead2: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            clientId?: string | null;
            client?: components["schemas"]["Client2"];
            /** Format: uuid */
            assignedToId?: string | null;
            assignedTo?: components["schemas"]["User"];
            status: components["schemas"]["LeadStatus"];
            procedency: string;
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
        };
        LeadCreateDto: {
            /** Format: uuid */
            clientId?: string | null;
            /** Format: uuid */
            assignedToId?: string | null;
            status: components["schemas"]["LeadStatus"];
            procedency: string;
        };
        /** @enum {unknown} */
        LeadStatus: "Registered" | "Attended";
        LeadTask: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            leadId: string;
            lead?: components["schemas"]["Lead"];
            /** Format: uuid */
            assignedToId: string;
            assignedTo?: components["schemas"]["User"];
            description: string;
            /** Format: date-time */
            scheduledDate: string;
            /** Format: date-time */
            completedDate?: string | null;
            isCompleted?: boolean;
            type?: components["schemas"]["TaskType"];
            isActive?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
        };
        LeadTaskCreateDto: {
            /** Format: uuid */
            leadId: string;
            /** Format: uuid */
            assignedToId: string;
            description: string;
            scheduledDate: string;
            type?: components["schemas"]["TaskType"];
        };
        LeadTaskUpdateDto: {
            /** Format: uuid */
            leadId?: string | null;
            /** Format: uuid */
            assignedToId?: string | null;
            description?: string | null;
            scheduledDate?: string | null;
            type?: components["schemas"]["NullableOfTaskType"];
            isCompleted?: boolean | null;
        };
        LeadUpdateDto: {
            /** Format: uuid */
            clientId?: string | null;
            /** Format: uuid */
            assignedToId?: string | null;
            status?: components["schemas"]["NullableOfLeadStatus"];
            procedency?: string | null;
        };
        LoginRequest: {
            /** @default admin@admin.com */
            email: string;
            /** @default Acide2025/1 */
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            refreshToken: string;
            /** Format: int32 */
            accessExpiresIn: number;
            /** Format: int32 */
            refreshExpiresIn: number;
        };
        /** @enum {unknown|null} */
        NullableOfClientType: "Natural" | "Juridico" | null;
        /** @enum {unknown|null} */
        NullableOfLeadStatus: "Registered" | "Attended" | null;
        /** @enum {unknown|null} */
        NullableOfTaskType: "Call" | "Meeting" | "Email" | "Visit" | "Other" | null;
        RefreshRequest: {
            refreshToken: string;
        };
        /** @enum {unknown} */
        TaskType: "Call" | "Meeting" | "Email" | "Visit" | "Other";
        User: {
            /** Format: date-time */
            lastLogin?: string | null;
            isActive?: boolean;
            mustChangePassword?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            modifiedAt?: string;
            /** Format: uuid */
            id?: string;
            userName?: string | null;
            normalizedUserName?: string | null;
            email?: string | null;
            normalizedEmail?: string | null;
            emailConfirmed?: boolean;
            passwordHash?: string | null;
            securityStamp?: string | null;
            concurrencyStamp?: string | null;
            phoneNumber?: string | null;
            phoneNumberConfirmed?: boolean;
            twoFactorEnabled?: boolean;
            /** Format: date-time */
            lockoutEnd?: string | null;
            lockoutEnabled?: boolean;
            /** Format: int32 */
            accessFailedCount?: number;
        } | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
