pipeline {
	agent any
	environment {
		BUILD_REF = sh(script: "echo -n '${BUILD_TAG}' | sha256sum | cut -c1-12", returnStdout: true).trim()

		PROJECT_NAME    = "gestionhogar"
		PROJECT_SERVICE = "frontend"
		PROJECT_STAGE   = "develop"

		REMOTE_USER   = "docker_admin"
		REMOTE_IP     = "localhost"
		REMOTE_FOLDER = "/home/docker_admin/${PROJECT_NAME}-${PROJECT_STAGE}/"

		REGISTRY_CREDENTIALS = "f16149d3-8913-40f9-80ff-9eca92eef798"
		REGISTRY_URL         = "docker.io"
		REGISTRY_USER        = "araozu"
		PROJECT_TRIPLET   = "${PROJECT_NAME}-${PROJECT_SERVICE}-${PROJECT_STAGE}"
		FULL_REGISTRY_URL = "${REGISTRY_URL}/${REGISTRY_USER}/${PROJECT_TRIPLET}"

		// SSH credentials
		SSH_CRED = "ssh-id_docker_admin_hetzner"

		// ansible variables
		PROJECT_SERVICES  = "backend,frontend,landing"
	}
	stages {
		stage("Create ansible inventory") {
			steps {
				dir ("+devops/+$PROJECT_STAGE") {
					writeFile(file: "inventory.yml", text: """
ungrouped:
  hosts:
    ${REMOTE_IP}:
      ansible_user: ${REMOTE_USER}
""")
				}
			}
		}
		stage("Build & Push") {
			parallel {
				stage("frontend") {
					stages {
						stage("Build & Push") {
							steps {
								script {
									def buildVariables = [
										NEXT_PUBLIC_BACKEND_URL: "https://gestionhogar-backend-develop.araozu.dev"
									]

									def dockerBuildArgs = new StringBuilder()
									buildVariables.each { key, value ->
										dockerBuildArgs.append("--build-arg ${key}=\"${value}\" ")
									}

									def finalDockerArgs = dockerBuildArgs.toString().trim()
									echo "Generated Docker Build Args: '${finalDockerArgs}'"

									withDockerRegistry(credentialsId: "${REGISTRY_CREDENTIALS}") {
										def image = docker.build("${FULL_REGISTRY_URL}:${BUILD_REF}", "${finalDockerArgs} -f +devops/docker/Dockerfile .")
										// image.push()
									}
								}
							}
						}
						stage("Fetch image at server") {
							steps {
								dir ("+devops/+$PROJECT_STAGE") {
									ansiblePlaybook(
										credentialsId: SSH_CRED,
										inventory: "inventory.yml",
										playbook: "../ansible/service_pull_and_setup.yml",
										vaultCredentialsId: "ansible-vault-gestionhogar-key",
										extras: "--extra-vars '@vault.yml'",
										extraVars: [
											_remote_folder: REMOTE_FOLDER,
											_image_tag: BUILD_REF,
											_full_registry_url: FULL_REGISTRY_URL,
											_project_name: PROJECT_NAME,
											_project_stage: PROJECT_STAGE,
											_project_service: PROJECT_SERVICE,
										],
									)
								}
							}
						}
					}
				}
				stage("Setup target") {
					steps {
						dir ("+devops/+$PROJECT_STAGE") {
							ansiblePlaybook(
								credentialsId: SSH_CRED,
								inventory: "inventory.yml",
								playbook: "../ansible/setup_target.yml",
								extraVars: [
									_remote_folder: REMOTE_FOLDER,
									_project_name: PROJECT_NAME,
									_project_stage: PROJECT_STAGE,
								],
							)
						}
					}
				}
			}
		}
		stage("Up services") {
			steps {
				dir ("+devops/+$PROJECT_STAGE") {
					ansiblePlaybook(
						credentialsId: SSH_CRED,
						inventory: "inventory.yml",
						playbook: "../ansible/start_service.yml",
						extraVars: [
							_remote_folder_path: REMOTE_FOLDER,
							_project_name: PROJECT_NAME,
							_project_services: PROJECT_SERVICES,
							_project_stage: PROJECT_STAGE,
							_project_service: PROJECT_SERVICE,
						],
					)
				}
			}
		}
	}
}
